---
- name: Ensure Oracle ASM Support package
  yum:
    name: oracleasm-support
    state: present

- name: Oracle ASMlib
  yum:
    name: '{{ oracle_rpm_directory }}/{{ item }}'
    state: present
  with_items: oracle_oracleasmlib_files
