---
- name: Copying DBCA template file
  shell: cp {{ item.0.path }}/assistants/dbca/templates/General_Purpose.dbc {{ item.1.dbca_template_file }}
  when: item.0.name == item.1.oracle_home
  with_nested:
  - oracle_db_homes
  - oracle_databases

- name: Modifying Oracle Database template file
  lineinfile: 
    dest: '{{ item.0.dbca_template_file }}'
    regexp: '^(\s+)(<option name="{{ item.1.name }}" value=")(.*)("/?>)'
    line: '\1\2{{ item.1.value }}\4'
    backrefs: yes
    state: present
  with_subelements:
  - oracle_databases
  - common_attributes

- name: Ensuring template file is owned by Oracle Software owner
  file: 
    dest: '{{ item.dbca_template_file }}'
    owner: '{{ oracle_db_owner_user_name }}'
    group: '{{ oracle_inventory_group_name }}'
    mode: '0664'
    state: file
  with_items: oracle_databases

- name: Installing Oracle Database
  shell: '{{ item.0.path }}/bin/dbca -silent -createDatabase -templateName {{ item.1.dbca_template_file
    }} -gdbName {{ item.1.db_name }} -sid {{ item.1.db_name }} -sysPassword {{ item.1.syspassword
    }} -systemPassword {{ item.1.systempassword }} -dbsnmpPassword {{ item.1.dbsnmppassword
    }} -emConfiguration LOCAL -storageType FS -datafileJarLocation {{ item.0.path
    }}/assistants/dbca/templates -characterset {{ item.1.characterset }} -obfuscatedPasswords
    false -sampleSchema false'
  sudo: true
  sudo_user: '{{ oracle_db_owner_user_name }}'
  when: item.0.name == item.1.oracle_home
  with_nested:
  - oracle_db_homes
  - oracle_databases

- name: Create service file to startup Database on boot using SysV
  template:
    dest: /etc/init.d/oracle_{{ item.1.db_name }}
    src: dbora.j2
    owner: root
    group: root
    mode: '0750'
  when: ansible_distribution_major_version in ["5", "6"] and item.0.name == item.1.oracle_home  
  with_nested:
  - oracle_db_homes
  - oracle_databases
  tags: dbservice

- name: Create service file to startup Database on boot using Systemd
  template:
    dest: /etc/systemd/system/oracle_{{ item.1.db_name }}.service  
    src: oracle.service.j2
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_major_version == "7" and item.0.name == item.1.oracle_home
  with_nested:
  - oracle_db_homes
  - oracle_databases
  tags: dbservice

- name: Reload Systemd
  shell: systemctl daemon-reload
  when: ansible_distribution_major_version == "7"
  tags: dbservice

- name: Ensure Database is running and started on system boot
  service: 
    name: oracle_{{ item.db_name }}
    state: running
    enabled: True
  with_items: oracle_databases
  tags: dbservice
