---
- name: Creating Oracle Inventory group
  group: name={{ oracle_inventory_group_name }} gid={{ oracle_inventory_group_id }} state=present

- name: Checking if Oracle 12c has to be installed
  set_fact: oracle_db_homes_12c=true
  when: item.version[:2] == "12"
  with_items: oracle_db_homes

- name: Creating Oracle Grid Infrastructure groups
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items:
    - name: "{{ oracle_gi_osdba_group_name }}"
      gid: "{{ oracle_gi_osdba_group_id }}"
    - name: "{{ oracle_gi_osoper_group_name }}"
      gid: "{{ oracle_gi_osoper_group_id }}"
    - name: "{{ oracle_gi_osasm_group_name }}"
      gid: "{{ oracle_gi_osasm_group_id }}"
  when: oracle_gi_homes is defined

- name: Creating Oracle Database groups
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items:
  - name: '{{ oracle_db_osdba_group_name }}'
    gid: '{{ oracle_db_osdba_group_id }}'
  - name: '{{ oracle_db_osoper_group_name }}'
    gid: '{{ oracle_db_osoper_group_id }}'
  when: oracle_db_homes is defined

- name: Creating Oracle Database groups (12c) 
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items:
  - name: '{{ oracle_db_osbackupdba_group_name }}'
    gid: '{{ oracle_db_osbackupdba_group_id }}'
  - name: '{{ oracle_db_osdgdba_group_name }}'
    gid: '{{ oracle_db_osdgdba_group_id }}'
  - name: '{{ oracle_db_oskmdba_group_name }}'
    gid: '{{ oracle_db_oskmdba_group_id }}'
  when: oracle_db_homes is defined and oracle_db_homes_12c
