---
- include_vars: '{{ oracle_db_home.edition }}-{{ oracle_db_home.version }}-{{ ansible_architecture }}.yml'

- name: Check if Oracle binary exists
  stat:
    path: '{{ oracle_db_home.path }}/bin/oracle'
  register: oracle_db_home_binary

- include: oracle_home.yml
  when: not oracle_db_home_binary.stat.exists
  tags: oracle_home

- include: listener.yml
  tags: oracle_listener

- include: dbca.yml
  tags: oracle_dbca

- name: Creating environment file
  template:
    src: set_env_DB.j2
    dest: '{{ oracle_db_owner_user_home }}/.set_env_{{ item.name }}'
    group: '{{ oracle_inventory_group_name }}'
    owner: '{{ oracle_db_owner_user_name }}'
    mode: '0664'
  with_items: oracle_databases
  tags: oracle_setenv
