---
- name: Get number of kernel lines in Grub config
  shell: grep -c {{ oracle_grub_regexp }} {{ oracle_grub_config_file }}
  register: grub_kernel_count
  changed_when: false
  tags:
  - elevator
  - thp
  - numa

- name: Setting Disk I/O Scheduler to deadline
  lineinfile:
    dest: '{{ oracle_grub_config_file }}'
    backrefs: true
    state: present
    regexp: (^\s+(kernel|linux16)(\s+(?!elevator=deadline)[\w=/\-\.]+)*)\s*$
    line: \1 elevator=deadline
  when: ansible_distribution_major_version|int > 5
  with_sequence: count={{ grub_kernel_count.stdout }}
  tags: elevator

- name: Disabling Transparent Hugepages
  lineinfile:
    dest: '{{ oracle_grub_config_file }}'
    backrefs: true
    state: present
    regexp: (^\s+(kernel|linux16)(\s+(?!transparent_hugepages=never)[\w=/\-\.]+)*)\s*$
    line: \1 transparent_hugepages=never
  when: ansible_distribution_major_version|int > 5
  with_sequence: count={{ grub_kernel_count.stdout }}
  tags: thp

- name: Disabling NUMA
  lineinfile:
    dest: '{{ oracle_grub_config_file }}'
    regexp: (^\s+(kernel|linux16)(\s+(?!numa=off)[\w=/\-\.]+)*)\s*$
    line: \1 numa=off
    backrefs: true
    state: present
  with_sequence: count={{ grub_kernel_count.stdout }}
  tags: numa
