---

- name: Ensure listener.ora
  template:
    dest: '{{ oracle_tns_admin }}/listener.ora'
    src: listener.ora.j2
    owner: '{{ oracle_db_owner_user_name }}'
    group: '{{ oracle_inventory_group_name }}'
    mode: '0664'
  register: oracle_listeners_stat

- name: Ensure Oracle Listener
  become: true
  become_method: sudo
  become_user: '{{ oracle_db_owner_user_name }}'
  oracle_listener:
    name: '{{ item.name }}'
    port: '{{ item.port }}'
    protocol: '{{ item.protocol }}'
    oracle_home: '{{ item.path }}'
    tns_admin: '{{ oracle_tns_admin }}'
    state: running
  with_items: oracle_listeners
