---
- name: Setting SELinux to permissive
  lineinfile:
    dest: /etc/selinux/config
    regexp: ^(SELINUX)=(enforcing)
    line: \1=permissive
    backrefs: true
    state: present
  register: selinux_config

- name: Modifying SELinux mode
  shell: setenforce Permissive
  when: selinux_config.changed